/*
 * Action types
 */
export const BOOTSTRAP_REFERENCE = 'BOOTSTRAP_REFERENCE'

/**
 * Actions for handling currentUser.
 */
export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST'
export const FETCH_CURRENT_USER_REQUEST_SUCCESS = 'FETCH_CURRENT_USER_REQUEST_SUCCESS'
export const FETCH_CURRENT_USER_REQUEST_FAILURE = 'FETCH_CURRENT_USER_REQUEST_FAILURE'
